### ISSUE TITLE
net-im/telegram-desktop version bump request to 1.2.6

### ISSUE THREAD

**Issue by jorgicio** [msva/mva-overlay#102]
Hi! I don't know if you're already working on that, but the title mentions it. 1.2.6 was released some time ago.

Thanks!

**Comment by shiba89** [comment]
Sorry to butt in, I found this https://github.com/reagentoo/gentoo-overlay/tree/master/net-im/telegram-desktop
For now I have no plans to upgrade to GCC 7 (system wide, at least) so I don't have the slightest idea whether it works or not.
