### ISSUE TITLE
net-im/telegram-desktop-1.2.17 fails to build

### ISSUE THREAD

**Issue by jorgicio** [msva/mva-overlay#103]
Hi!

This happens when I try to build the 1.2.17 version of telegram-desktop.
https://paste.pound-python.org/show/VDUV2iMgnkR1UsQpo8pd/

I'm using gcc 6.4.0 (the stable one).

Thanks!

emerge --info: https://paste.pound-python.org/show/rjHYKPsw8Cr5aUKmBrb2/

**Comment by msva** [comment]
Well, I heard, there is a requirement of gcc7 on the Telegram side, but I'm not sure if this is the case.

Can you, please, check following:
0) does 9999 version compiles for you with your current setup?
1) does the code compiles with clang (`СС=clang CXX=clang++ emerge -O1 telegram-desktop`, requires clang installed) on your system?
2) does the code compiles with gcc-7.3.0 (`CC=x86_64-pc-linux-gnu-gcc-7.3.0 CXX=x86_64-pc-linux-gnu-g++-7.3.0 emerge -O1 telegram-desktop`, requires gcc-7.3.0 to be installed, but you can keep your current compiler as default, and don't switch to gcc7) on your system?

**Comment by jorgicio** [comment]
Tried with 9999 version, and it throws the same output as above.
Also tried with clang 5.0 (I'm using the stable one) and it fails too much later: https://bpaste.net/show/f01fa31cb5b0

As I'm using the (kinda) stable profile, I don't use masked packages, so I can't try it with gcc 7.3.0. Sorry.

I think it definitively needs gcc >= 7.

**Comment by jorgicio** [comment]
In fact, it needs GCC 7. Some days ago, GCC 7.3.0 became stable, so I upgraded it and now I can build telegram-desktop flawlessly.
You may consider to add a pkg_pretend to verify the GCC version installed first.

Anyways, thanks.
