### ISSUE TITLE
net-im/telegram-desktop bump to 1.7.13

### ISSUE THREAD

**Issue by Anonymous1157** [msva/mva-overlay#121]
Hi! Thanks for writing/maintaining this ebuild, it works really well.

Telegram has officially released support for animated stickers, which means older versions that did unofficially support and display them correctly have been retroactively made incompatible and won't load them any more (!?!?!?). Anyway, 1.7.13 is now required for the new feature.

**Comment by msva** [comment]
I know about that, but they f*cked up all the things too much (including 
"using private Qt functions" as one of many things they doing wrong), and it 
is problematic to build it against system (shared) Qt for now.
So, I'm investigating the way to fix it again.

// and they're lmost relesed .14 already, btw
