### ISSUE TITLE
net-im/telegram-desktop-1.9.3: clang useflag doesn't use clang

### ISSUE THREAD

**Issue by Anonymous1157** [msva/mva-overlay#134]
There's no `-DCMAKE_C_COMPILER={CHOST}-clang` etc. lines in the ebuild, so the useflag doesn't seem to do anything but force GCC to use libcxx. Then the build fails linking against media-libs/rlottie[libcxx] whereas it works when clang/libcxx useflags aren't enabled. I suspect that part will fix itself when this ebuild actually uses clang...

**Comment by msva** [comment]
well, actually there was a check for current `${CXX}` being `clang*`, but now I changed that part to proper clang detection, so it should work now.

Feel free to ask to reopen, if it is still an issue for you.

**Comment by Anonymous1157** [comment]
I thought because the useflag was called clang that the ebuild was supposed to automatically build with clang, but it looks like you intended for users to use package.env instead. Now the ebuilds for rlottie, libtgvoip, telegram-desktop are all consistent that there's a libcxx flag and it does not automatically use clang, and that makes more sense.
