### ISSUE TITLE
[QUESTION] Will you mind on upstreaming telegram-desktop to gentoo main repo?

### ISSUE THREAD

**Issue by scardracs** [msva/mva-overlay#145]
I'm actually using your overlay for telegram-desktop and I wondering if you are interested on uploading your ebuild to gentoo main repo. Thanks

**Comment by msva** [comment]
I have plas on this, but it will need some rework for that. And currently I've not anough spare time, unfortunately.

Maybe a bit later...

**Comment by scardracs** [comment]
> I have plas on this, but it will need some rework for that. And currently I've not anough spare time, unfortunately.
> 
> Maybe a bit later...

I have seen that there is a new maintainer for version in gentoo repo
