### ISSUE TITLE
Nginx Pagespeed failure

### ISSUE THREAD

**Issue by drillsar** [msva/mva-overlay#147]
I got the following errors:

!!! Fetched file: nginx.pagespeed-1.12.34.2.tar.gz VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      118610
!!! Expected: 118562
Refetching... File renamed to '/var/cache/distfiles/nginx.pagespeed-1.12.34.2.tar.gz._checksum_failure_.zhhsh3uk'

!!! Couldn't download 'nginx.pagespeed-1.12.34.2.tar.gz'. Aborting.
 * Fetch failed for 'www-nginx/pagespeed-1.12.34.2', Log file:
 *  '/var/tmp/portage/www-nginx/pagespeed-1.12.34.2/temp/build.log'

>>> Failed to emerge www-nginx/pagespeed-1.12.34.2, Log file:

**Comment by msva** [comment]
Well, looks like either MITM or google guys changing tarballs after release...

**Comment by msva** [comment]
Well, anyways, there is new version in use in current ngx ebuild already
