### ISSUE TITLE
Upstream telepathy-haze to Guru

### ISSUE THREAD

**Issue by ran-dall** [msva/mva-overlay#150]
Hello @msva! Hope all is well. I wanted to ask you if it was okay if I used your telepathy-haze.ebuild as a source for an upstream telepathy-haze.ebuild on Guru? 

An PR was opened before to re-add to the main tree, but it was suggested that a better home for it would be on Guru, hence my question. Specifically, your ebuild is already using `EAPI=8` and is using a more updated version(s) of Python. You can see the PR here: https://github.com/gentoo/gentoo/pull/20204.

**Comment by msva** [comment]
@ran-dall Yup, I'm okay to giveaway it to guru repo if someone will take maintenance and will not forget to update it.

// although, since I generally still not using Guru repo on any of my Gentoos repo for some reason, I'm not sure whether I will drop it here in near future :)
