### ISSUE TITLE
some dev-lua/resty-* ebuilds incorrectly depend on nginx having LUA_USEDEP

### ISSUE THREAD

**Issue by tgbugs** [msva/mva-overlay#155]
There are a number of dependencies of the form
`www-servers/nginx:*[${LUA_USEDEP},nginx_modules_http_lua]`
that are broken with the current `www-servers/nginx-1.21.6-r10` ebuild because it does not specify any `LUA_COMPAT`. I'm not sure what the correct fix is. Adding `LUA_COMPAT` to the nginx ebuild and interiting the lua eclass seems to fix the issue, but I'm guessing that was removed for a reason? The other solution is to remove all the `${LUA_USEDEP},` restrictions from the dependencies.

**Comment by msva** [comment]
Actually, I've already removed LUA_USEDEP from resty-* ebuilds few days ago...

**Comment by msva** [comment]
https://github.com/msva/mva-overlay/commit/135be6911baeefa3f8a0d88280ff86e5b5f41fea

(few hours after issue was created, but I didn't notice the issue that moment).

So, I'll consider it "fixed". If you'll found some not fixed one - feel free to leave a comment about that here.
