### ISSUE TITLE
net-im/telegram-cli-9999 configure: error: No supported python lib version found.

### ISSUE THREAD

**Issue by devakrit** [msva/mva-overlay#178]
hi.
I'm trying to install this ebuild from the overlay. Unfortunately I'm getting an error. Attached is the failed build log.
[build.log](https://github.com/msva/mva-overlay/files/13684381/build.log)

This is with python disabled.

[ebuild  N    *] net-im/telegram-cli-9999::mva  USE="-json -lua -python" LUA_SINGLE_TARGET="-lua5-1 -lua5-3 -lua5-4 -luajit" PYTHON_SINGLE_TARGET="-python3_10 -python3_11 -python3_12" 0 KiB

**Comment by msva** [comment]
Actually, it is dead for a long time (last commit was about a 7 years ago), and it is totally broken and can't build anyway for some time.

Please, consider using tdlib and some wrapper around it instead.
