### ISSUE TITLE
`app-text/ltex-ls`: dependency `dev-java/failureaccess` not in the tree anymore

### ISSUE THREAD

**Issue by gerion0** [msva/mva-overlay#183]
`dev-java/failureaccess` is a dependency of `app-text/ltex-ls` but was removed from the tree in https://github.com/gentoo/gentoo/commit/b01474d.

**Comment by gerion0** [comment]
Here is the revert of the above linked commit that adds the ebuild back into a tree [0001-Revert-dev-java-failureaccess-Remove-last-rited-pkg.patch](https://github.com/user-attachments/files/15968622/0001-Revert-dev-java-failureaccess-Remove-last-rited-pkg.txt) (I had to rename it to txt since Github didn't want a patch file).

**Comment by msva** [comment]
fixed in 84c1b6d7

**Comment by gerion0** [comment]
Thanks, I left some comments in the commit.
