### ISSUE TITLE
dev-java/gradle doesn't compile with Java 21.

### ISSUE THREAD

**Issue by MarkusTieger** [msva/mva-overlay#186]
The error:
```
This build requires JDK 11. It's currently /usr/lib64/openjdk-21. You can ignore this check by passing '-Dorg.gradle.ignoreBuildJavaVersionCheck=true'.
```

Current workarround:
- Set the default java to 11

And ofc:
```
!!! When you file a bug report, please include the following information:
GENTOO_VM=  CLASSPATH="" JAVA_HOME=""
JAVACFLAGS="" COMPILER=""
```

And after that a sandbox access violation:
[sandbox.log](https://github.com/user-attachments/files/16324542/sandbox.log)

**Comment by msva** [comment]
have you tried with 8.10?

**Comment by MarkusTieger** [comment]
> have you tried with 8.10?

yes

**Comment by MarkusTieger** [comment]
Any updates?

**Comment by msva** [comment]
should be fixed with 8.10.2 (it says it has support for jdk up to 23)

(just pushed)

**Comment by MarkusTieger** [comment]
> should be fixed with 8.10.2 (it says it has support for jdk up to 23)
> 
> (just pushed)

nope

**Comment by msva** [comment]
![image](https://github.com/user-attachments/assets/9ffaaabb-81a4-41b6-b451-ee154397cbb4)
Well, then they are liars...

Well, I'll try to add that flag then

**Comment by msva** [comment]
by the way, can you post the full buildlog, please?

**Comment by msva** [comment]
also, it is pretty interesting, that it builds fine here for me :shrug:, and also it falls back to bundled jdk :thinking:
It is pretty strange, that it doesn't happen for you

**Comment by MarkusTieger** [comment]
> ![image](https://private-user-images.githubusercontent.com/268102/373889088-9ffaaabb-81a4-41b6-b451-ee154397cbb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxNDk1NzUsIm5iZiI6MTcyODE0OTI3NSwicGF0aCI6Ii8yNjgxMDIvMzczODg5MDg4LTlmZmFhYWJiLTgxYTQtNDFiNi1iNDUxLWVlMTU0Mzk3Y2JiNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQxNzI3NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTNkMGE4ODU1ZmEwNGRkMGVjNTU3ZTliZWExNTIxZmZkMmQ2MDZkZjdkM2YwMGYyMmYzNTE1N2I3YmMyMjJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UZ0Ups2DY7nHnj98bCrXHgsm1lyTPZjjE0m7zLgpVY0) Well, then they are liars...
> 
> Well, I'll try to add that flag then

No they are not. Java 23 is supported, but in runtime, not for compiling.

**Comment by MarkusTieger** [comment]
> by the way, can you post the full buildlog, please?

I don't think this is necessary. Java 11 is hardcoded: https://github.com/gradle/gradle/blob/master/settings.gradle.kts#L333

**Comment by msva** [comment]
should be fixed now
