### ISSUE TITLE
Update app-crypt/etoken-sac to new version of SAC

### ISSUE THREAD

**Issue by vladykin** [msva/mva-overlay#28]
Looks like a new version of SafenetAuthenticationClient is available. I've got such files:
SafenetAuthenticationClient-8.3.34-0.x86_64.rpm
SAC-32-CompatibilityPack-8.3.34-0.x86_64.rpm

Could you please update your ebuild to this new version?
Thanks!

**Comment by msva** [comment]
I need that files to update the ebuild (for Manifest generation).
Can you forward me a Aladdin's email, including attached archive with that files, they mailed you?

**Comment by vladykin** [comment]
I've got the files from http://online.payment.ru/index0.html?support
