### ISSUE TITLE
app-crypt/etoken-sac-8.3.34_p0

### ISSUE THREAD

**Issue by arbitrary-dev** [msva/mva-overlay#31]
Just stopped by to report a newer version of eToken driver: 9.0.43-0

**Comment by msva** [comment]
Do you have distfiles for it? ;)

**Comment by arbitrary-dev** [comment]
Here you go, man:
http://rghost.net/8cJD9LSDM

**Comment by arbitrary-dev** [comment]
There is an error in your current ebuild for x86 architecture in line 63, there should be:
local arch=i386;
