### ISSUE TITLE
media-libs/libquvi-0.9.4-r1 malformed dependency

### ISSUE THREAD

**Issue by fuzzyray** [msva/mva-overlay#34]
See Gentoo bug 550862,

The virtual/lua dependency in RDEPEND has a type causing a malformed dependency:

virtual/lua[luajit=,${MULTILIB_USEDEP}] )

The ')' character at the end is an error and needs to be removed.

**Comment by msva** [comment]
// unfortunately sometimes I commit ebuilds from smartphone, where running repoman is PITA :-/
The strange thing is that emerge never complained on that :-/
