### ISSUE TITLE
www-servers/nginx-1.9.1: build failures in passenger if multiple RUBY_TARGETS are set

### ISSUE THREAD

**Issue by infoman** [msva/mva-overlay#36]
When trying to build nginx with passenger for both ruby-2.0 and 2.2, multiple error messages appear in the compilation process. Seems that there are some collisions between the two builds.

Full build log posted at http://pastebin.com/prPrap0g

**Comment by msva** [comment]
Does it build fine if you trying to build 
with USE="-ruby_targets_ruby22" emerge 
nginx::mva?

// i.e. without 2.2, just to check, that error is 
non on the ruby2.0 side? :)

**Comment by infoman** [comment]
Yes, it builds correctly with 2.2 only and 2.0 only, but not both of them.

**Comment by msva** [comment]
Uhm... I'm tested few workarounds last night, but I 
have to say that it is pretty hard to bundle multiple 
Passenger copies into NginX without HEAVY 
patching (rewriting functions names, Makefiles, 
configs and so on) which can brake it in runtime. So, 
sorry, but I'll make NginX+Passenger to only build 
against one and only one ruby_target. Sorry, if it will 
brake some your plans.

P.S. let's wait for shared modules support, which 
should be done somewhere in 1.9.* ;)

**Comment by msva** [comment]
@infoman 
Good news. I've kinda fixed the issue (it now builds against ruby selected with `eselect` and installs helpers to all enabled `RUBY_TARGETS`.
Although, I'm not sure if it will not have any side-effects at runtime.

Also, I'm trying to force passenger to unbundle it's libuv and libev, and latter can produce some explosion too. So, if you'll experience some troubles, please report.
