### ISSUE TITLE
net-p2p/syncthing-9999::mva failed build

### ISSUE THREAD

**Issue by transserg** [msva/mva-overlay#41]
>>> Emerging (1 of 1) net-p2p/syncthing-9999::mva
>>> Unpacking source...
 * Fetching https://github.com/syncthing/syncthing ...
git fetch https://github.com/syncthing/syncthing +HEAD:refs/git-r3/HEAD
git symbolic-ref refs/git-r3/net-p2p/syncthing/0/__main__ refs/heads/master
 * Checking out https://github.com/syncthing/syncthing to /var/tmp/portage/net-p2p/syncthing-9999/work/syncthing-9999/src/github.com/syncthing/syncthing ...
git checkout --quiet master
GIT update -->
   repository:               https://github.com/syncthing/syncthing
   at the commit:            aaf6bf3cd209f4fcb6d12bcc999f90c009f9853e
>>> Source unpacked in /var/tmp/portage/net-p2p/syncthing-9999/work
>>> Preparing source in /var/tmp/portage/net-p2p/syncthing-9999/work/syncthing-9999/src/github.com/syncthing/syncthing ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/net-p2p/syncthing-9999/work/syncthing-9999/src/github.com/syncthing/syncthing ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/net-p2p/syncthing-9999/work/syncthing-9999/src/github.com/syncthing/syncthing ...
# github.com/syncthing/syncthing/cmd/syncthing
cmd/syncthing/gui.go:776: too many arguments in call to upgrade.LatestRelease
cmd/syncthing/gui.go:819: too many arguments in call to upgrade.LatestRelease
cmd/syncthing/main.go:350: too many arguments in call to upgrade.LatestRelease
cmd/syncthing/main.go:1071: too many arguments in call to upgrade.LatestRelease
godep: go exit status 2
>>> Source compiled.
>>> Test phase [not enabled]: net-p2p/syncthing-9999

>>> Install syncthing-9999 into /var/tmp/portage/net-p2p/syncthing-9999/image/ category net-p2p
!!! dobin: syncthing does not exist
 * ERROR: net-p2p/syncthing-9999::mva failed (install phase):
 *   dobin failed
 * 
 * If you need support, post the output of `emerge --info '=net-p2p/syncthing-9999::mva'`,
 * the complete build log and the output of `emerge -pqv '=net-p2p/syncthing-9999::mva'`.
 * The complete build log is located at '/var/tmp/portage/net-p2p/syncthing-9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/net-p2p/syncthing-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/net-p2p/syncthing-9999/work/syncthing-9999/src/github.com/syncthing/syncthing'
 * S: '/var/tmp/portage/net-p2p/syncthing-9999/work/syncthing-9999/src/github.com/syncthing/syncthing'
 * QA Notice: file does not exist:
 * 
 * 	dobin: syncthing does not exist

>>> Failed to emerge net-p2p/syncthing-9999, Log file:

>>>  '/var/tmp/portage/net-p2p/syncthing-9999/temp/build.log'

**Comment by msva** [comment]
I just installed it fine right now. There is binary at it's place and no installation error.

Can you provide, at least, emerge --info?

**Comment by msva** [comment]
Uhm, stop, no need in emerge --info. There was probably just error in sources. It is 9999, if any.
