### ISSUE TITLE
dev-libs/librevenge-9999 fails to merge

### ISSUE THREAD

**Issue by p-kozlov** [msva/mva-overlay#76]
```
configure: error: Package requirements (cppunit) were not met:

No package 'cppunit' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables CPPUNIT_CFLAGS
and CPPUNIT_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```
Of course cppunit is not installed, good idea to add it to dependencies to ebuild.

And from my point of view it's not good idea to add keywords `amd64` and `x86` to 9999 packages, what do you think?

**Comment by msva** [comment]
> And from my point of view it's not good idea to add keywords `amd64` and
> `x86` to 9999 packages, what do you think?

Of course. It seems, I just missed it when bumped from stable version
(by the way, there is also 9999 in portage now, I'll check if it has valid 
deps (and other things) and if it has better values, I'll just drop it here. 
Do you have any objections?
