### ISSUE TITLE
www-client/yandex-browser-beta-16.9.1.466_p1 fails to install

### ISSUE THREAD

**Issue by cerebrum** [msva/mva-overlay#79]
emerge -1 www-client/yandex-browser-beta
...
>>> Completed installing yandex-browser-beta-16.9.1.466_p1 into /var/tmp/portage/www-client/yandex-browser-beta-16.9.1.466_p1/image/

 * Final size of build directory: 0 KiB
 * Final size of installed tree: 182060 KiB

scanelf: rpath_security_checks(): Security problem with DT_RPATH='$ORIGIN/.' in /var/tmp/portage/www-client/yandex-browser-beta-16.9.1.466_p1/image/opt/yandex/browser-beta/yandex_browser-sandbox with mode set of 4711
scanelf: rpath_security_checks(): Security problem with DT_RPATH='$ORIGIN/.' in /var/tmp/portage/www-client/yandex-browser-beta-16.9.1.466_p1/image/opt/yandex/browser-beta/yandex_browser-sandbox with mode set of 4711

 * QA Notice: The following files contain insecure RUNPATHs
 *  Please file a bug about this at http://bugs.gentoo.org/
 *  with the maintaining herd of the package.
 * $ORIGIN/. /var/tmp/portage/www-client/yandex-browser-beta-16.9.1.466_p1/image/opt/yandex/browser-beta/yandex_browser-sandbox

 * ERROR: www-client/yandex-browser-beta-16.9.1.466_p1::mva failed:
 *   Aborting due to serious QA concerns with RUNPATH/RPATH

**Comment by msva** [comment]
unfortunately, it is hard to fix RPATH issue in proprietary software.
Normally, it can be set (or hacked around) during linking at build time.
And I can remember no ways to fix RPATHs on precompiled software.
So, ideally, that should be reported upstream.
// although, anyway, ping @kapsh @alexws54tk

**Comment by alexws54tk** [comment]
@msva, I am simply fixing .ebuild in #80 and writing this info to Yandex team.

**Comment by msva** [comment]
fixed by #80
