### ISSUE TITLE
net-im/telegram-desktop-1.1.7 bump request

### ISSUE THREAD

**Issue by jorgicio** [msva/mva-overlay#93]
Hi! Yesterday, the 1.1.7 version of Telegram Desktop was released, so I request the bump of the source-based version, please.

Thanks in advance.

**Comment by reagentoo** [comment]
Actually, it is not tar source-based version.:)

**Comment by jorgicio** [comment]
I never mentioned anything about a tar ._.

**Comment by msva** [comment]
> I never mentioned anything about a tar ._.

Neither I :)
