### ISSUE TITLE
nginx-related issue when syncing or doing an emerge @world

### ISSUE THREAD

**Issue by jorgicio** [msva/mva-overlay#95]
This happens everytime I sync overlays and do an emerge @world:

`Calculating dependencies |/var/lib/layman/mva/www-servers/nginx/nginx-1.13.2.ebuild: line 191: syntax error near unexpected token `<<<'
/var/lib/layman/mva/www-servers/nginx/nginx-1.13.2.ebuild: line 191: `<<<<<<< HEAD:www-servers/nginx/nginx-1.13.2.ebuild'
 * ERROR: www-servers/nginx-1.13.2::mva failed (depend phase):
 *   error sourcing ebuild
 * 
 * Call stack:
 *   ebuild.sh, line 611:  Called die
 * The specific snippet of code:
 *   			source "$EBUILD" || die "error sourcing ebuild"
 * 
 * If you need support, post the output of `emerge --info '=www-servers/nginx-1.13.2::mva'`,
 - * the complete build log and the output of `emerge -pqv '=www-servers/nginx-1.13.2::mva'`.
 * Working directory: '/usr/lib64/python2.7/site-packages'
 * S: '/var/tmp/portage/www-servers/nginx-1.13.2/work/nginx-1.13.2'
... done!
`

Thanks

**Comment by myallod** [comment]
+1

**Comment by msva** [comment]
I'm not sure, how was that happened, but try to remove and re-add the overlay. 
It should help.

**Comment by jorgicio** [comment]
@msva You're right, I tried that and it worked. The error message is gone.
Thanks.
